# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Filetug < Formula
  desc "FileTug – modern CLI file browser/picker with neat UI"
  homepage "https://github.com/datatug/filetug"
  version "0.0.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datatug/filetug/releases/download/v0.0.17/filetug_0.0.17_darwin_amd64.tar.gz"
      sha256 "c4ab05c6655846e9c230e26fb5ee0d900e9d4db4b693a01eb74e62f1089dccf7"

      def install
        bin.install "filetug"
        (bin/"filetug").install_symlink "ft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/datatug/filetug/releases/download/v0.0.17/filetug_0.0.17_darwin_arm64.tar.gz"
      sha256 "b33dfb1500d260f94f3f9f398968c92e50b4d562d3abdd7c0b5b5fc9cfd558c2"

      def install
        bin.install "filetug"
        (bin/"filetug").install_symlink "ft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/datatug/filetug/releases/download/v0.0.17/filetug_0.0.17_linux_amd64.tar.gz"
      sha256 "e51e87e7e0addc9001948b951600982f1f4a05ba44a56e6cdee1cc030b2eb9db"
      def install
        bin.install "filetug"
        (bin/"filetug").install_symlink "ft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datatug/filetug/releases/download/v0.0.17/filetug_0.0.17_linux_arm64.tar.gz"
      sha256 "24346b038e3bc0b55380e81d0debf26ef8222e53d36e5b7d5f6be423976a93dd"
      def install
        bin.install "filetug"
        (bin/"filetug").install_symlink "ft"
      end
    end
  end

  test do
    system "#{bin}/filetug", "--version"
    system "#{bin}/ft", "--version"
  end
end
